version: "3"

services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "5000:5000"
    env_file: ./backend/.env
    networks:
      - eskolah-network
    command: ["yarn", "dev"]
    environment:
      - MONGO_URI=${MONGO_URI}
      - MONGO_DB=${MONGO_DB}
    depends_on:
      - db
  db:
    image: mongo:latest
    volumes:
      - data:/data/db
    ports:
      - "27017:27017"
    networks:
      - eskolah-network
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend/:/usr/src/web
      - /usr/src/web/node_modules
      - /usr/src/web/.next
    env_file: ./frontend/.env
    ports:
      - "3000:3000"
    networks:
      - eskolah-network
    command: ["yarn", "dev"]

networks:
  eskolah-network:
    driver: bridge

volumes:
  data:
